# Generated by Django 5.2.3 on 2025-11-02 17:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('worker', 'Worker'), ('employer', 'Employer'), ('admin', 'Admin')], default='worker', max_length=20)),
                ('trust_score', models.FloatField(default=0.0)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('level', models.IntegerField(default=1)),
                ('xp_points', models.IntegerField(default=0)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
